# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    defaults:
      run:
        working-directory: buildAndReleaseTask
    env:
      NODE_ENV: ci
    runs-on: ubuntu-latest
    container:
      image: node:10
    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
          npm install
          npm run compile
          npm test
          npm install tfx-cli -g
          ../package.sh
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist/
  package:
    needs: [build]
    env: 
      NODE_ENV: ci
    runs-on: ubuntu-latest
    container:
      image: node:10
    steps:
      - name: Package
        run: | 
          npm install tfx-cli -g
          ./package.sh
