# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      NODE_ENV: ci
    runs-on: ubuntu-latest
    container:
      image: node:10
    steps:
      - uses: actions/checkout@v1
        
      - name: Build & Tests
        working-directory: buildAndReleaseTask
        run: |
          npm install
          npm run compile
          npm test
          
      - name: Package
        run: | 
          npm install tfx-cli -g
          ./package.sh
          ./publish.sh
